# Generated by Django 4.2.5 on 2024-07-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_userreport_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='text',
        ),
    ]
