# Generated by Django 4.2.5 on 2024-07-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_userreport_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='user',
        ),
    ]
