# Generated by Django 4.2.5 on 2024-07-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_userreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='file',
        ),
        migrations.AddField(
            model_name='userreport',
            name='diagnosis_file',
            field=models.FileField(blank=True, null=True, upload_to='user_reports/'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='report_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='user_reports/'),
        ),
    ]
